compressionLevel: mixed

enableConstraintsChecks: true

enableGlobalCache: true

enableScripts: false

httpTimeout: 300000

nodeLinker: node-modules

npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - "@safe-global/*"

packageExtensions:
  eslint-config-next@*:
    peerDependencies:
      next: "*"

supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - linux
    - darwin
