events {}
http {
 include /etc/nginx/mime.types;
 server {
 listen 8080;
 server_tokens off;
 root /usr/share/nginx/html;
 # BEGIN FINNEY TRUSTED BATCHES
 location ~* ^/finney-decoder/api/v1/contracts/0x40A2aCCbd92BCA938b02010E17A5b8929b49130D/?$ {
  default_type application/json;
  if ($arg_chain_ids != "964") { return 200 '{"count":0,"next":null,"previous":null,"results":[]}'; }
  return 200 '{"count":1,"next":null,"previous":null,"results":[{"address":"0x40A2aCCbd92BCA938b02010E17A5b8929b49130D","name":"MultiSendCallOnly","displayName":"Safe MultiSendCallOnly 1.3.0","chainId":964,"project":null,"abi":null,"modified":"2026-09-29T00:00:00Z","trustedForDelegateCall":true}]}';
 }
 location ~* ^/finney-decoder/api/v1/contracts/0x9641d764fc13c8B624c04430C7356C1C7C8102e2/?$ {
  default_type application/json;
  if ($arg_chain_ids != "964") { return 200 '{"count":0,"next":null,"previous":null,"results":[]}'; }
  return 200 '{"count":1,"next":null,"previous":null,"results":[{"address":"0x9641d764fc13c8B624c04430C7356C1C7C8102e2","name":"MultiSendCallOnly","displayName":"Safe MultiSendCallOnly 1.4.1","chainId":964,"project":null,"abi":null,"modified":"2026-09-29T00:00:00Z","trustedForDelegateCall":true}]}';
 }
 location /finney-decoder/ {
  proxy_ssl_server_name on;
  proxy_set_header Host safe-decoder.safe.global;
  proxy_pass https://safe-decoder.safe.global/;
 }
 # END FINNEY TRUSTED BATCHES
 location = /healthz { return 200 'ok'; }
 location /address-resolver/ { proxy_pass http://address-resolver:8090/; proxy_set_header Host $host; }
 location /cgw/ { proxy_pass http://cgw:3000/; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
 location ~ ^/txs/api/v1/about/?$ { return 404; }
 location /txs/api/ { proxy_pass http://txs:8888/api/; proxy_set_header Host $host; }
 location = /tx-builder { rewrite ^ /tx-builder/index.html last; }
 location /tx-builder/ { try_files $uri $uri/ /tx-builder/index.html; }
 location / { try_files $uri $uri.html $uri/ =404; }
 }
}
